; Listing generated by Microsoft (R) Optimizing Compiler Version 19.00.24215.1 

	TITLE	C:\Windows\fastgh3\PLUGINS\CODE\gh3\GlobalMap.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMTD
INCLUDELIB OLDNAMES

CONST	SEGMENT
?tab@crc32@GH3@@3QBIB DD 00H				; GH3::crc32::tab
	DD	077073096H
	DD	0ee0e612cH
	DD	0990951baH
	DD	076dc419H
	DD	0706af48fH
	DD	0e963a535H
	DD	09e6495a3H
	DD	0edb8832H
	DD	079dcb8a4H
	DD	0e0d5e91eH
	DD	097d2d988H
	DD	09b64c2bH
	DD	07eb17cbdH
	DD	0e7b82d07H
	DD	090bf1d91H
	DD	01db71064H
	DD	06ab020f2H
	DD	0f3b97148H
	DD	084be41deH
	DD	01adad47dH
	DD	06ddde4ebH
	DD	0f4d4b551H
	DD	083d385c7H
	DD	0136c9856H
	DD	0646ba8c0H
	DD	0fd62f97aH
	DD	08a65c9ecH
	DD	014015c4fH
	DD	063066cd9H
	DD	0fa0f3d63H
	DD	08d080df5H
	DD	03b6e20c8H
	DD	04c69105eH
	DD	0d56041e4H
	DD	0a2677172H
	DD	03c03e4d1H
	DD	04b04d447H
	DD	0d20d85fdH
	DD	0a50ab56bH
	DD	035b5a8faH
	DD	042b2986cH
	DD	0dbbbc9d6H
	DD	0acbcf940H
	DD	032d86ce3H
	DD	045df5c75H
	DD	0dcd60dcfH
	DD	0abd13d59H
	DD	026d930acH
	DD	051de003aH
	DD	0c8d75180H
	DD	0bfd06116H
	DD	021b4f4b5H
	DD	056b3c423H
	DD	0cfba9599H
	DD	0b8bda50fH
	DD	02802b89eH
	DD	05f058808H
	DD	0c60cd9b2H
	DD	0b10be924H
	DD	02f6f7c87H
	DD	058684c11H
	DD	0c1611dabH
	DD	0b6662d3dH
	DD	076dc4190H
	DD	01db7106H
	DD	098d220bcH
	DD	0efd5102aH
	DD	071b18589H
	DD	06b6b51fH
	DD	09fbfe4a5H
	DD	0e8b8d433H
	DD	07807c9a2H
	DD	0f00f934H
	DD	09609a88eH
	DD	0e10e9818H
	DD	07f6a0dbbH
	DD	086d3d2dH
	DD	091646c97H
	DD	0e6635c01H
	DD	06b6b51f4H
	DD	01c6c6162H
	DD	0856530d8H
	DD	0f262004eH
	DD	06c0695edH
	DD	01b01a57bH
	DD	08208f4c1H
	DD	0f50fc457H
	DD	065b0d9c6H
	DD	012b7e950H
	DD	08bbeb8eaH
	DD	0fcb9887cH
	DD	062dd1ddfH
	DD	015da2d49H
	DD	08cd37cf3H
	DD	0fbd44c65H
	DD	04db26158H
	DD	03ab551ceH
	DD	0a3bc0074H
	DD	0d4bb30e2H
	DD	04adfa541H
	DD	03dd895d7H
	DD	0a4d1c46dH
	DD	0d3d6f4fbH
	DD	04369e96aH
	DD	0346ed9fcH
	DD	0ad678846H
	DD	0da60b8d0H
	DD	044042d73H
	DD	033031de5H
	DD	0aa0a4c5fH
	DD	0dd0d7cc9H
	DD	05005713cH
	DD	0270241aaH
	DD	0be0b1010H
	DD	0c90c2086H
	DD	05768b525H
	DD	0206f85b3H
	DD	0b966d409H
	DD	0ce61e49fH
	DD	05edef90eH
	DD	029d9c998H
	DD	0b0d09822H
	DD	0c7d7a8b4H
	DD	059b33d17H
	DD	02eb40d81H
	DD	0b7bd5c3bH
	DD	0c0ba6cadH
	DD	0edb88320H
	DD	09abfb3b6H
	DD	03b6e20cH
	DD	074b1d29aH
	DD	0ead54739H
	DD	09dd277afH
	DD	04db2615H
	DD	073dc1683H
	DD	0e3630b12H
	DD	094643b84H
	DD	0d6d6a3eH
	DD	07a6a5aa8H
	DD	0e40ecf0bH
	DD	09309ff9dH
	DD	0a00ae27H
	DD	07d079eb1H
	DD	0f00f9344H
	DD	08708a3d2H
	DD	01e01f268H
	DD	06906c2feH
	DD	0f762575dH
	DD	0806567cbH
	DD	0196c3671H
	DD	06e6b06e7H
	DD	0fed41b76H
	DD	089d32be0H
	DD	010da7a5aH
	DD	067dd4accH
	DD	0f9b9df6fH
	DD	08ebeeff9H
	DD	017b7be43H
	DD	060b08ed5H
	DD	0d6d6a3e8H
	DD	0a1d1937eH
	DD	038d8c2c4H
	DD	04fdff252H
	DD	0d1bb67f1H
	DD	0a6bc5767H
	DD	03fb506ddH
	DD	048b2364bH
	DD	0d80d2bdaH
	DD	0af0a1b4cH
	DD	036034af6H
	DD	041047a60H
	DD	0df60efc3H
	DD	0a867df55H
	DD	0316e8eefH
	DD	04669be79H
	DD	0cb61b38cH
	DD	0bc66831aH
	DD	0256fd2a0H
	DD	05268e236H
	DD	0cc0c7795H
	DD	0bb0b4703H
	DD	0220216b9H
	DD	05505262fH
	DD	0c5ba3bbeH
	DD	0b2bd0b28H
	DD	02bb45a92H
	DD	05cb36a04H
	DD	0c2d7ffa7H
	DD	0b5d0cf31H
	DD	02cd99e8bH
	DD	05bdeae1dH
	DD	09b64c2b0H
	DD	0ec63f226H
	DD	0756aa39cH
	DD	026d930aH
	DD	09c0906a9H
	DD	0eb0e363fH
	DD	072076785H
	DD	05005713H
	DD	095bf4a82H
	DD	0e2b87a14H
	DD	07bb12baeH
	DD	0cb61b38H
	DD	092d28e9bH
	DD	0e5d5be0dH
	DD	07cdcefb7H
	DD	0bdbdf21H
	DD	086d3d2d4H
	DD	0f1d4e242H
	DD	068ddb3f8H
	DD	01fda836eH
	DD	081be16cdH
	DD	0f6b9265bH
	DD	06fb077e1H
	DD	018b74777H
	DD	088085ae6H
	DD	0ff0f6a70H
	DD	066063bcaH
	DD	011010b5cH
	DD	08f659effH
	DD	0f862ae69H
	DD	0616bffd3H
	DD	0166ccf45H
	DD	0a00ae278H
	DD	0d70dd2eeH
	DD	04e048354H
	DD	03903b3c2H
	DD	0a7672661H
	DD	0d06016f7H
	DD	04969474dH
	DD	03e6e77dbH
	DD	0aed16a4aH
	DD	0d9d65adcH
	DD	040df0b66H
	DD	037d83bf0H
	DD	0a9bcae53H
	DD	0debb9ec5H
	DD	047b2cf7fH
	DD	030b5ffe9H
	DD	0bdbdf21cH
	DD	0cabac28aH
	DD	053b39330H
	DD	024b4a3a6H
	DD	0bad03605H
	DD	0cdd70693H
	DD	054de5729H
	DD	023d967bfH
	DD	0b3667a2eH
	DD	0c4614ab8H
	DD	05d681b02H
	DD	02a6f2b94H
	DD	0b40bbe37H
	DD	0c30c8ea1H
	DD	05a05df1bH
	DD	02d02ef8dH
CONST	ENDS
PUBLIC	?fixChar@crc32@GH3@@YADD@Z			; GH3::crc32::fixChar
PUBLIC	?hashChar@crc32@GH3@@YAIDI@Z			; GH3::crc32::hashChar
PUBLIC	?hash@crc32@GH3@@YAIPBDI@Z			; GH3::crc32::hash
PUBLIC	??0QbKey@GH3@@QAE@XZ				; GH3::QbKey::QbKey
PUBLIC	??0QbKey@GH3@@QAE@ABU01@@Z			; GH3::QbKey::QbKey
PUBLIC	??0QbKey@GH3@@QAE@I@Z				; GH3::QbKey::QbKey
PUBLIC	??0QbKey@GH3@@QAE@PBD@Z				; GH3::QbKey::QbKey
PUBLIC	??BQbKey@GH3@@QBEIXZ				; GH3::QbKey::operator unsigned int
PUBLIC	??4QbKey@GH3@@QAEAAU01@I@Z			; GH3::QbKey::operator=
PUBLIC	??4QbKey@GH3@@QAEAAU01@ABU01@@Z			; GH3::QbKey::operator=
PUBLIC	??4QbPair@GH3@@QAEAAU01@ABU01@@Z		; GH3::QbPair::operator=
PUBLIC	??4QbPair@GH3@@QAEAAU01@$$QAU01@@Z		; GH3::QbPair::operator=
PUBLIC	??4QbVector@GH3@@QAEAAU01@ABU01@@Z		; GH3::QbVector::operator=
PUBLIC	??4QbVector@GH3@@QAEAAU01@$$QAU01@@Z		; GH3::QbVector::operator=
PUBLIC	?Set@QbArray@GH3@@QAEXHI@Z			; GH3::QbArray::Set
PUBLIC	?Get@QbArray@GH3@@QBEIH@Z			; GH3::QbArray::Get
PUBLIC	?SetType@QbArray@GH3@@QAEXW4QbValueType@2@@Z	; GH3::QbArray::SetType
PUBLIC	?Type@QbArray@GH3@@QBE?AW4QbValueType@2@XZ	; GH3::QbArray::Type
PUBLIC	?Length@QbArray@GH3@@QBEIXZ			; GH3::QbArray::Length
PUBLIC	??4QbArray@GH3@@QAEAAU01@ABU01@@Z		; GH3::QbArray::operator=
PUBLIC	??4QbArray@GH3@@QAEAAU01@$$QAU01@@Z		; GH3::QbArray::operator=
PUBLIC	?Type@QbStructItem@GH3@@QAE?AW4QbValueType@2@XZ	; GH3::QbStructItem::Type
PUBLIC	??4QbStructItem@GH3@@QAEAAU01@ABU01@@Z		; GH3::QbStructItem::operator=
PUBLIC	??4QbStructItem@GH3@@QAEAAU01@$$QAU01@@Z	; GH3::QbStructItem::operator=
PUBLIC	??4QbStruct@GH3@@QAEAAU01@ABU01@@Z		; GH3::QbStruct::operator=
PUBLIC	?Get@QbMap@GH3@@QBEIUQbKey@2@@Z			; GH3::QbMap::Get
PUBLIC	?Insert@QbMap@GH3@@QAEXUQbKey@2@I@Z		; GH3::QbMap::Insert
PUBLIC	?Size@QbMap@GH3@@QBEIXZ				; GH3::QbMap::Size
PUBLIC	?Type@QbMap@GH3@@QBE?AW4QbValueType@2@XZ	; GH3::QbMap::Type
PUBLIC	?IndexMask@QbMap@GH3@@QBEIXZ			; GH3::QbMap::IndexMask
PUBLIC	??4QbMap@GH3@@QAEAAU01@ABU01@@Z			; GH3::QbMap::operator=
PUBLIC	??4QbMap@GH3@@QAEAAU01@$$QAU01@@Z		; GH3::QbMap::operator=
PUBLIC	?Size@GlobalMap@GH3@@SAIXZ			; GH3::GlobalMap::Size
PUBLIC	?Length@GlobalMap@GH3@@SAIXZ			; GH3::GlobalMap::Length
PUBLIC	?IndexMask@GlobalMap@GH3@@SAIXZ			; GH3::GlobalMap::IndexMask
PUBLIC	?Nodes@GlobalMap@GH3@@SAPAPAUHashMapNode@2@XZ	; GH3::GlobalMap::Nodes
PUBLIC	?GetEntry@GlobalMap@GH3@@SAPAUHashMapNode@2@UQbKey@2@@Z ; GH3::GlobalMap::GetEntry
PUBLIC	?GetTypedValue@GlobalMap@GH3@@SA_NUQbKey@2@W4QbValueType@2@PAX@Z ; GH3::GlobalMap::GetTypedValue
PUBLIC	?GetValue@GlobalMap@GH3@@SA_NUQbKey@2@PAXPAW4QbValueType@2@@Z ; GH3::GlobalMap::GetValue
PUBLIC	??4GlobalMap@GH3@@QAEAAV01@ABV01@@Z		; GH3::GlobalMap::operator=
EXTRN	??AQbArray@GH3@@QBEIH@Z:PROC			; GH3::QbArray::operator[]
EXTRN	??AQbArray@GH3@@QAEAAIH@Z:PROC			; GH3::QbArray::operator[]
EXTRN	??AQbMap@GH3@@QBEIUQbKey@1@@Z:PROC		; GH3::QbMap::operator[]
EXTRN	??AQbMap@GH3@@QAEAAIUQbKey@1@@Z:PROC		; GH3::QbMap::operator[]
EXTRN	__RTC_CheckEsp:PROC
EXTRN	__RTC_InitBase:PROC
EXTRN	__RTC_Shutdown:PROC
EXTRN	__fltused:DWORD
;	COMDAT rtc$TMZ
rtc$TMZ	SEGMENT
__RTC_Shutdown.rtc$TMZ DD FLAT:__RTC_Shutdown
rtc$TMZ	ENDS
;	COMDAT rtc$IMZ
rtc$IMZ	SEGMENT
__RTC_InitBase.rtc$IMZ DD FLAT:__RTC_InitBase
rtc$IMZ	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
;	COMDAT ??4GlobalMap@GH3@@QAEAAV01@ABV01@@Z
_TEXT	SEGMENT
_this$ = -8						; size = 4
___that$ = 8						; size = 4
??4GlobalMap@GH3@@QAEAAV01@ABV01@@Z PROC		; GH3::GlobalMap::operator=, COMDAT
; _this$ = ecx
	push	ebp
	mov	ebp, esp
	sub	esp, 204				; 000000ccH
	push	ebx
	push	esi
	push	edi
	push	ecx
	lea	edi, DWORD PTR [ebp-204]
	mov	ecx, 51					; 00000033H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	pop	ecx
	mov	DWORD PTR _this$[ebp], ecx
	mov	eax, DWORD PTR _this$[ebp]
	pop	edi
	pop	esi
	pop	ebx
	mov	esp, ebp
	pop	ebp
	ret	4
??4GlobalMap@GH3@@QAEAAV01@ABV01@@Z ENDP		; GH3::GlobalMap::operator=
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
; File c:\windows\fastgh3\plugins\code\gh3\globalmap.cpp
;	COMDAT ?GetValue@GlobalMap@GH3@@SA_NUQbKey@2@PAXPAW4QbValueType@2@@Z
_TEXT	SEGMENT
_pValue2$ = -20						; size = 4
_node$ = -8						; size = 4
_key$ = 8						; size = 4
_pValue$ = 12						; size = 4
_pType$ = 16						; size = 4
?GetValue@GlobalMap@GH3@@SA_NUQbKey@2@PAXPAW4QbValueType@2@@Z PROC ; GH3::GlobalMap::GetValue, COMDAT

; 28   : 	{

	push	ebp
	mov	ebp, esp
	sub	esp, 228				; 000000e4H
	push	ebx
	push	esi
	push	edi
	lea	edi, DWORD PTR [ebp-228]
	mov	ecx, 57					; 00000039H
	mov	eax, -858993460				; ccccccccH
	rep stosd

; 29   : 		HashMapNode *node = GetEntry(key);

	push	ecx
	mov	ecx, esp
	lea	eax, DWORD PTR _key$[ebp]
	push	eax
	call	??0QbKey@GH3@@QAE@ABU01@@Z		; GH3::QbKey::QbKey
	call	?GetEntry@GlobalMap@GH3@@SAPAUHashMapNode@2@UQbKey@2@@Z ; GH3::GlobalMap::GetEntry
	add	esp, 4
	mov	DWORD PTR _node$[ebp], eax

; 30   : 		uint32_t *pValue2 = reinterpret_cast<uint32_t *>(pValue); //We don't know what type of data is being stored besides that it's 32 bits but that's all we need.

	mov	eax, DWORD PTR _pValue$[ebp]
	mov	DWORD PTR _pValue2$[ebp], eax
$LN2@GetValue:

; 31   : 
; 32   : 		while (node != nullptr)

	cmp	DWORD PTR _node$[ebp], 0
	je	SHORT $LN3@GetValue

; 33   : 		{
; 34   : 			if (node->key == key)

	mov	ecx, DWORD PTR _node$[ebp]
	add	ecx, 4
	call	??BQbKey@GH3@@QBEIXZ			; GH3::QbKey::operator unsigned int
	mov	esi, eax
	lea	ecx, DWORD PTR _key$[ebp]
	call	??BQbKey@GH3@@QBEIXZ			; GH3::QbKey::operator unsigned int
	cmp	esi, eax
	jne	SHORT $LN4@GetValue

; 35   : 			{
; 36   : 				if (pValue2 != nullptr)

	cmp	DWORD PTR _pValue2$[ebp], 0
	je	SHORT $LN5@GetValue

; 37   : 					*pValue2 = node->value;

	mov	eax, DWORD PTR _pValue2$[ebp]
	mov	ecx, DWORD PTR _node$[ebp]
	mov	edx, DWORD PTR [ecx+12]
	mov	DWORD PTR [eax], edx
$LN5@GetValue:

; 38   : 				if (pType != nullptr)

	cmp	DWORD PTR _pType$[ebp], 0
	je	SHORT $LN6@GetValue

; 39   : 					*pType = node->itemType;

	mov	eax, DWORD PTR _pType$[ebp]
	mov	ecx, DWORD PTR _node$[ebp]
	mov	dl, BYTE PTR [ecx+2]
	mov	BYTE PTR [eax], dl
$LN6@GetValue:

; 40   : 				return true;

	mov	al, 1
	jmp	SHORT $LN1@GetValue
$LN4@GetValue:

; 41   : 			}
; 42   : 			node = node->nextItem;

	mov	eax, DWORD PTR _node$[ebp]
	mov	ecx, DWORD PTR [eax+16]
	mov	DWORD PTR _node$[ebp], ecx

; 43   : 		}

	jmp	SHORT $LN2@GetValue
$LN3@GetValue:

; 44   : 
; 45   : 		if (pValue2 != nullptr)

	cmp	DWORD PTR _pValue2$[ebp], 0
	je	SHORT $LN7@GetValue

; 46   : 			*pValue2 = 0;

	mov	eax, DWORD PTR _pValue2$[ebp]
	mov	DWORD PTR [eax], 0
$LN7@GetValue:

; 47   : 		if (pType != nullptr)

	cmp	DWORD PTR _pType$[ebp], 0
	je	SHORT $LN8@GetValue

; 48   : 			*pType = QbValueType::TypeUndefined;

	mov	eax, DWORD PTR _pType$[ebp]
	mov	BYTE PTR [eax], 0
$LN8@GetValue:

; 49   : 		return false;

	xor	al, al
$LN1@GetValue:

; 50   : 	}

	pop	edi
	pop	esi
	pop	ebx
	add	esp, 228				; 000000e4H
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	0
?GetValue@GlobalMap@GH3@@SA_NUQbKey@2@PAXPAW4QbValueType@2@@Z ENDP ; GH3::GlobalMap::GetValue
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
; File c:\windows\fastgh3\plugins\code\gh3\globalmap.cpp
;	COMDAT ?GetTypedValue@GlobalMap@GH3@@SA_NUQbKey@2@W4QbValueType@2@PAX@Z
_TEXT	SEGMENT
_pValue2$ = -20						; size = 4
_node$ = -8						; size = 4
_key$ = 8						; size = 4
_type$ = 12						; size = 1
_pValue$ = 16						; size = 4
?GetTypedValue@GlobalMap@GH3@@SA_NUQbKey@2@W4QbValueType@2@PAX@Z PROC ; GH3::GlobalMap::GetTypedValue, COMDAT

; 7    : 	{

	push	ebp
	mov	ebp, esp
	sub	esp, 228				; 000000e4H
	push	ebx
	push	esi
	push	edi
	lea	edi, DWORD PTR [ebp-228]
	mov	ecx, 57					; 00000039H
	mov	eax, -858993460				; ccccccccH
	rep stosd

; 8    : 		HashMapNode *node = GetEntry(key);

	push	ecx
	mov	ecx, esp
	lea	eax, DWORD PTR _key$[ebp]
	push	eax
	call	??0QbKey@GH3@@QAE@ABU01@@Z		; GH3::QbKey::QbKey
	call	?GetEntry@GlobalMap@GH3@@SAPAUHashMapNode@2@UQbKey@2@@Z ; GH3::GlobalMap::GetEntry
	add	esp, 4
	mov	DWORD PTR _node$[ebp], eax

; 9    : 		uint32_t *pValue2 = reinterpret_cast<uint32_t *>(pValue); //We don't know what type of data is being stored besides that it's 32 bits but that's all we need.

	mov	eax, DWORD PTR _pValue$[ebp]
	mov	DWORD PTR _pValue2$[ebp], eax
$LN2@GetTypedVa:

; 10   : 
; 11   : 		while (node != nullptr)

	cmp	DWORD PTR _node$[ebp], 0
	je	SHORT $LN3@GetTypedVa

; 12   : 		{
; 13   : 			if (node->key == key && node->itemType == type)

	mov	ecx, DWORD PTR _node$[ebp]
	add	ecx, 4
	call	??BQbKey@GH3@@QBEIXZ			; GH3::QbKey::operator unsigned int
	mov	esi, eax
	lea	ecx, DWORD PTR _key$[ebp]
	call	??BQbKey@GH3@@QBEIXZ			; GH3::QbKey::operator unsigned int
	cmp	esi, eax
	jne	SHORT $LN4@GetTypedVa
	mov	eax, DWORD PTR _node$[ebp]
	movsx	ecx, BYTE PTR [eax+2]
	movsx	edx, BYTE PTR _type$[ebp]
	cmp	ecx, edx
	jne	SHORT $LN4@GetTypedVa

; 14   : 			{
; 15   : 				if (pValue2 != nullptr)

	cmp	DWORD PTR _pValue2$[ebp], 0
	je	SHORT $LN5@GetTypedVa

; 16   : 					*pValue2 = node->value;

	mov	eax, DWORD PTR _pValue2$[ebp]
	mov	ecx, DWORD PTR _node$[ebp]
	mov	edx, DWORD PTR [ecx+12]
	mov	DWORD PTR [eax], edx
$LN5@GetTypedVa:

; 17   : 				return true;

	mov	al, 1
	jmp	SHORT $LN1@GetTypedVa
$LN4@GetTypedVa:

; 18   : 			}
; 19   : 			node = node->nextItem;

	mov	eax, DWORD PTR _node$[ebp]
	mov	ecx, DWORD PTR [eax+16]
	mov	DWORD PTR _node$[ebp], ecx

; 20   : 		}

	jmp	SHORT $LN2@GetTypedVa
$LN3@GetTypedVa:

; 21   : 
; 22   : 		if (pValue2 != nullptr)

	cmp	DWORD PTR _pValue2$[ebp], 0
	je	SHORT $LN6@GetTypedVa

; 23   : 			*pValue2 = 0;

	mov	eax, DWORD PTR _pValue2$[ebp]
	mov	DWORD PTR [eax], 0
$LN6@GetTypedVa:

; 24   : 		return false;

	xor	al, al
$LN1@GetTypedVa:

; 25   : 	}

	pop	edi
	pop	esi
	pop	ebx
	add	esp, 228				; 000000e4H
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	0
?GetTypedValue@GlobalMap@GH3@@SA_NUQbKey@2@W4QbValueType@2@PAX@Z ENDP ; GH3::GlobalMap::GetTypedValue
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
; File c:\windows\fastgh3\plugins\code\gh3\globalmap.h
;	COMDAT ?GetEntry@GlobalMap@GH3@@SAPAUHashMapNode@2@UQbKey@2@@Z
_TEXT	SEGMENT
_key$ = 8						; size = 4
?GetEntry@GlobalMap@GH3@@SAPAUHashMapNode@2@UQbKey@2@@Z PROC ; GH3::GlobalMap::GetEntry, COMDAT

; 32   : 		inline static HashMapNode * GetEntry(QbKey key) { return Nodes()[key & IndexMask()]; };

	push	ebp
	mov	ebp, esp
	sub	esp, 192				; 000000c0H
	push	ebx
	push	esi
	push	edi
	lea	edi, DWORD PTR [ebp-192]
	mov	ecx, 48					; 00000030H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	call	?Nodes@GlobalMap@GH3@@SAPAPAUHashMapNode@2@XZ ; GH3::GlobalMap::Nodes
	mov	esi, eax
	lea	ecx, DWORD PTR _key$[ebp]
	call	??BQbKey@GH3@@QBEIXZ			; GH3::QbKey::operator unsigned int
	mov	edi, eax
	call	?IndexMask@GlobalMap@GH3@@SAIXZ		; GH3::GlobalMap::IndexMask
	and	edi, eax
	mov	eax, DWORD PTR [esi+edi*4]
	pop	edi
	pop	esi
	pop	ebx
	add	esp, 192				; 000000c0H
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	0
?GetEntry@GlobalMap@GH3@@SAPAUHashMapNode@2@UQbKey@2@@Z ENDP ; GH3::GlobalMap::GetEntry
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
; File c:\windows\fastgh3\plugins\code\gh3\globalmap.h
;	COMDAT ?Nodes@GlobalMap@GH3@@SAPAPAUHashMapNode@2@XZ
_TEXT	SEGMENT
?Nodes@GlobalMap@GH3@@SAPAPAUHashMapNode@2@XZ PROC	; GH3::GlobalMap::Nodes, COMDAT

; 30   : 		inline static HashMapNode ** Nodes() { return reinterpret_cast<HashMapNode **>(0x00C03AA8); };

	push	ebp
	mov	ebp, esp
	sub	esp, 192				; 000000c0H
	push	ebx
	push	esi
	push	edi
	lea	edi, DWORD PTR [ebp-192]
	mov	ecx, 48					; 00000030H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	mov	eax, 12597928				; 00c03aa8H
	pop	edi
	pop	esi
	pop	ebx
	mov	esp, ebp
	pop	ebp
	ret	0
?Nodes@GlobalMap@GH3@@SAPAPAUHashMapNode@2@XZ ENDP	; GH3::GlobalMap::Nodes
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
; File c:\windows\fastgh3\plugins\code\gh3\globalmap.h
;	COMDAT ?IndexMask@GlobalMap@GH3@@SAIXZ
_TEXT	SEGMENT
?IndexMask@GlobalMap@GH3@@SAIXZ PROC			; GH3::GlobalMap::IndexMask, COMDAT

; 28   : 		inline static constexpr uint32_t IndexMask() { return Length() - 1; }

	push	ebp
	mov	ebp, esp
	sub	esp, 192				; 000000c0H
	push	ebx
	push	esi
	push	edi
	lea	edi, DWORD PTR [ebp-192]
	mov	ecx, 48					; 00000030H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	call	?Length@GlobalMap@GH3@@SAIXZ		; GH3::GlobalMap::Length
	sub	eax, 1
	pop	edi
	pop	esi
	pop	ebx
	add	esp, 192				; 000000c0H
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	0
?IndexMask@GlobalMap@GH3@@SAIXZ ENDP			; GH3::GlobalMap::IndexMask
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
; File c:\windows\fastgh3\plugins\code\gh3\globalmap.h
;	COMDAT ?Length@GlobalMap@GH3@@SAIXZ
_TEXT	SEGMENT
?Length@GlobalMap@GH3@@SAIXZ PROC			; GH3::GlobalMap::Length, COMDAT

; 27   : 		inline static constexpr uint32_t Length() { return 1 << Size(); }

	push	ebp
	mov	ebp, esp
	sub	esp, 192				; 000000c0H
	push	ebx
	push	esi
	push	edi
	lea	edi, DWORD PTR [ebp-192]
	mov	ecx, 48					; 00000030H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	call	?Size@GlobalMap@GH3@@SAIXZ		; GH3::GlobalMap::Size
	mov	edx, 1
	mov	ecx, eax
	shl	edx, cl
	mov	eax, edx
	pop	edi
	pop	esi
	pop	ebx
	add	esp, 192				; 000000c0H
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	0
?Length@GlobalMap@GH3@@SAIXZ ENDP			; GH3::GlobalMap::Length
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
; File c:\windows\fastgh3\plugins\code\gh3\globalmap.h
;	COMDAT ?Size@GlobalMap@GH3@@SAIXZ
_TEXT	SEGMENT
?Size@GlobalMap@GH3@@SAIXZ PROC				; GH3::GlobalMap::Size, COMDAT

; 26   : 		inline static constexpr uint32_t Size() { return 15; }

	push	ebp
	mov	ebp, esp
	sub	esp, 192				; 000000c0H
	push	ebx
	push	esi
	push	edi
	lea	edi, DWORD PTR [ebp-192]
	mov	ecx, 48					; 00000030H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	mov	eax, 15					; 0000000fH
	pop	edi
	pop	esi
	pop	ebx
	mov	esp, ebp
	pop	ebp
	ret	0
?Size@GlobalMap@GH3@@SAIXZ ENDP				; GH3::GlobalMap::Size
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
;	COMDAT ??4QbMap@GH3@@QAEAAU01@$$QAU01@@Z
_TEXT	SEGMENT
_this$ = -8						; size = 4
___that$ = 8						; size = 4
??4QbMap@GH3@@QAEAAU01@$$QAU01@@Z PROC			; GH3::QbMap::operator=, COMDAT
; _this$ = ecx
	push	ebp
	mov	ebp, esp
	sub	esp, 204				; 000000ccH
	push	ebx
	push	esi
	push	edi
	push	ecx
	lea	edi, DWORD PTR [ebp-204]
	mov	ecx, 51					; 00000033H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	pop	ecx
	mov	DWORD PTR _this$[ebp], ecx
	mov	eax, DWORD PTR _this$[ebp]
	mov	ecx, DWORD PTR ___that$[ebp]
	mov	edx, DWORD PTR [ecx]
	mov	DWORD PTR [eax], edx
	mov	eax, DWORD PTR _this$[ebp]
	mov	ecx, DWORD PTR ___that$[ebp]
	mov	edx, DWORD PTR [ecx+4]
	mov	DWORD PTR [eax+4], edx
	mov	eax, DWORD PTR _this$[ebp]
	mov	ecx, DWORD PTR ___that$[ebp]
	mov	dl, BYTE PTR [ecx+8]
	mov	BYTE PTR [eax+8], dl
	mov	eax, DWORD PTR _this$[ebp]
	mov	ecx, DWORD PTR ___that$[ebp]
	mov	edx, DWORD PTR [ecx+12]
	mov	DWORD PTR [eax+12], edx
	mov	eax, DWORD PTR _this$[ebp]
	mov	ecx, DWORD PTR ___that$[ebp]
	mov	edx, DWORD PTR [ecx+16]
	mov	DWORD PTR [eax+16], edx
	mov	eax, DWORD PTR _this$[ebp]
	mov	ecx, DWORD PTR ___that$[ebp]
	mov	dl, BYTE PTR [ecx+20]
	mov	BYTE PTR [eax+20], dl
	mov	eax, DWORD PTR _this$[ebp]
	mov	ecx, DWORD PTR ___that$[ebp]
	mov	dl, BYTE PTR [ecx+21]
	mov	BYTE PTR [eax+21], dl
	mov	eax, DWORD PTR _this$[ebp]
	mov	ecx, DWORD PTR ___that$[ebp]
	mov	dl, BYTE PTR [ecx+22]
	mov	BYTE PTR [eax+22], dl
	mov	eax, DWORD PTR _this$[ebp]
	mov	ecx, DWORD PTR ___that$[ebp]
	mov	dl, BYTE PTR [ecx+23]
	mov	BYTE PTR [eax+23], dl
	mov	eax, DWORD PTR _this$[ebp]
	pop	edi
	pop	esi
	pop	ebx
	mov	esp, ebp
	pop	ebp
	ret	4
??4QbMap@GH3@@QAEAAU01@$$QAU01@@Z ENDP			; GH3::QbMap::operator=
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
;	COMDAT ??4QbMap@GH3@@QAEAAU01@ABU01@@Z
_TEXT	SEGMENT
_this$ = -8						; size = 4
___that$ = 8						; size = 4
??4QbMap@GH3@@QAEAAU01@ABU01@@Z PROC			; GH3::QbMap::operator=, COMDAT
; _this$ = ecx
	push	ebp
	mov	ebp, esp
	sub	esp, 204				; 000000ccH
	push	ebx
	push	esi
	push	edi
	push	ecx
	lea	edi, DWORD PTR [ebp-204]
	mov	ecx, 51					; 00000033H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	pop	ecx
	mov	DWORD PTR _this$[ebp], ecx
	mov	eax, DWORD PTR ___that$[ebp]
	mov	ecx, DWORD PTR _this$[ebp]
	mov	edx, DWORD PTR [eax]
	mov	DWORD PTR [ecx], edx
	mov	edx, DWORD PTR [eax+4]
	mov	DWORD PTR [ecx+4], edx
	mov	edx, DWORD PTR [eax+8]
	mov	DWORD PTR [ecx+8], edx
	mov	edx, DWORD PTR [eax+12]
	mov	DWORD PTR [ecx+12], edx
	mov	edx, DWORD PTR [eax+16]
	mov	DWORD PTR [ecx+16], edx
	mov	eax, DWORD PTR [eax+20]
	mov	DWORD PTR [ecx+20], eax
	mov	eax, DWORD PTR _this$[ebp]
	pop	edi
	pop	esi
	pop	ebx
	mov	esp, ebp
	pop	ebp
	ret	4
??4QbMap@GH3@@QAEAAU01@ABU01@@Z ENDP			; GH3::QbMap::operator=
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
; File c:\windows\fastgh3\plugins\code\gh3\qbmap.h
;	COMDAT ?IndexMask@QbMap@GH3@@QBEIXZ
_TEXT	SEGMENT
_this$ = -8						; size = 4
?IndexMask@QbMap@GH3@@QBEIXZ PROC			; GH3::QbMap::IndexMask, COMDAT
; _this$ = ecx

; 43   : 		inline uint32_t IndexMask() const { return ( (1 << m_size) - 1); }

	push	ebp
	mov	ebp, esp
	sub	esp, 204				; 000000ccH
	push	ebx
	push	esi
	push	edi
	push	ecx
	lea	edi, DWORD PTR [ebp-204]
	mov	ecx, 51					; 00000033H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	pop	ecx
	mov	DWORD PTR _this$[ebp], ecx
	mov	eax, DWORD PTR _this$[ebp]
	mov	edx, 1
	mov	ecx, DWORD PTR [eax]
	shl	edx, cl
	sub	edx, 1
	mov	eax, edx
	pop	edi
	pop	esi
	pop	ebx
	mov	esp, ebp
	pop	ebp
	ret	0
?IndexMask@QbMap@GH3@@QBEIXZ ENDP			; GH3::QbMap::IndexMask
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
; File c:\windows\fastgh3\plugins\code\gh3\qbmap.h
;	COMDAT ?Type@QbMap@GH3@@QBE?AW4QbValueType@2@XZ
_TEXT	SEGMENT
_this$ = -8						; size = 4
?Type@QbMap@GH3@@QBE?AW4QbValueType@2@XZ PROC		; GH3::QbMap::Type, COMDAT
; _this$ = ecx

; 42   : 		inline QbValueType Type() const { return static_cast<QbValueType>(m_typeFlags >> 1); }

	push	ebp
	mov	ebp, esp
	sub	esp, 204				; 000000ccH
	push	ebx
	push	esi
	push	edi
	push	ecx
	lea	edi, DWORD PTR [ebp-204]
	mov	ecx, 51					; 00000033H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	pop	ecx
	mov	DWORD PTR _this$[ebp], ecx
	mov	eax, DWORD PTR _this$[ebp]
	movsx	eax, BYTE PTR [eax+8]
	sar	eax, 1
	pop	edi
	pop	esi
	pop	ebx
	mov	esp, ebp
	pop	ebp
	ret	0
?Type@QbMap@GH3@@QBE?AW4QbValueType@2@XZ ENDP		; GH3::QbMap::Type
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
; File c:\windows\fastgh3\plugins\code\gh3\qbmap.h
;	COMDAT ?Size@QbMap@GH3@@QBEIXZ
_TEXT	SEGMENT
_this$ = -8						; size = 4
?Size@QbMap@GH3@@QBEIXZ PROC				; GH3::QbMap::Size, COMDAT
; _this$ = ecx

; 41   : 		inline uint32_t Size() const { return m_size; }

	push	ebp
	mov	ebp, esp
	sub	esp, 204				; 000000ccH
	push	ebx
	push	esi
	push	edi
	push	ecx
	lea	edi, DWORD PTR [ebp-204]
	mov	ecx, 51					; 00000033H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	pop	ecx
	mov	DWORD PTR _this$[ebp], ecx
	mov	eax, DWORD PTR _this$[ebp]
	mov	eax, DWORD PTR [eax]
	pop	edi
	pop	esi
	pop	ebx
	mov	esp, ebp
	pop	ebp
	ret	0
?Size@QbMap@GH3@@QBEIXZ ENDP				; GH3::QbMap::Size
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
; File c:\windows\fastgh3\plugins\code\gh3\qbmap.h
;	COMDAT ?Insert@QbMap@GH3@@QAEXUQbKey@2@I@Z
_TEXT	SEGMENT
_this$ = -8						; size = 4
_key$ = 8						; size = 4
_value$ = 12						; size = 4
?Insert@QbMap@GH3@@QAEXUQbKey@2@I@Z PROC		; GH3::QbMap::Insert, COMDAT
; _this$ = ecx

; 39   : 		inline void Insert(QbKey key, uint32_t value) { this->operator[](key) = value; };

	push	ebp
	mov	ebp, esp
	sub	esp, 216				; 000000d8H
	push	ebx
	push	esi
	push	edi
	push	ecx
	lea	edi, DWORD PTR [ebp-216]
	mov	ecx, 54					; 00000036H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	pop	ecx
	mov	DWORD PTR _this$[ebp], ecx
	push	ecx
	mov	ecx, esp
	lea	eax, DWORD PTR _key$[ebp]
	push	eax
	call	??0QbKey@GH3@@QAE@ABU01@@Z		; GH3::QbKey::QbKey
	mov	ecx, DWORD PTR _this$[ebp]
	call	??AQbMap@GH3@@QAEAAIUQbKey@1@@Z		; GH3::QbMap::operator[]
	mov	ecx, DWORD PTR _value$[ebp]
	mov	DWORD PTR [eax], ecx
	pop	edi
	pop	esi
	pop	ebx
	add	esp, 216				; 000000d8H
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	8
?Insert@QbMap@GH3@@QAEXUQbKey@2@I@Z ENDP		; GH3::QbMap::Insert
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
; File c:\windows\fastgh3\plugins\code\gh3\qbmap.h
;	COMDAT ?Get@QbMap@GH3@@QBEIUQbKey@2@@Z
_TEXT	SEGMENT
_this$ = -8						; size = 4
_key$ = 8						; size = 4
?Get@QbMap@GH3@@QBEIUQbKey@2@@Z PROC			; GH3::QbMap::Get, COMDAT
; _this$ = ecx

; 38   : 		inline uint32_t Get(QbKey key) const { return (*this)[key]; };

	push	ebp
	mov	ebp, esp
	sub	esp, 216				; 000000d8H
	push	ebx
	push	esi
	push	edi
	push	ecx
	lea	edi, DWORD PTR [ebp-216]
	mov	ecx, 54					; 00000036H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	pop	ecx
	mov	DWORD PTR _this$[ebp], ecx
	push	ecx
	mov	ecx, esp
	lea	eax, DWORD PTR _key$[ebp]
	push	eax
	call	??0QbKey@GH3@@QAE@ABU01@@Z		; GH3::QbKey::QbKey
	mov	ecx, DWORD PTR _this$[ebp]
	call	??AQbMap@GH3@@QBEIUQbKey@1@@Z		; GH3::QbMap::operator[]
	pop	edi
	pop	esi
	pop	ebx
	add	esp, 216				; 000000d8H
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	4
?Get@QbMap@GH3@@QBEIUQbKey@2@@Z ENDP			; GH3::QbMap::Get
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
;	COMDAT ??4QbStruct@GH3@@QAEAAU01@ABU01@@Z
_TEXT	SEGMENT
_this$ = -8						; size = 4
___that$ = 8						; size = 4
??4QbStruct@GH3@@QAEAAU01@ABU01@@Z PROC			; GH3::QbStruct::operator=, COMDAT
; _this$ = ecx
	push	ebp
	mov	ebp, esp
	sub	esp, 204				; 000000ccH
	push	ebx
	push	esi
	push	edi
	push	ecx
	lea	edi, DWORD PTR [ebp-204]
	mov	ecx, 51					; 00000033H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	pop	ecx
	mov	DWORD PTR _this$[ebp], ecx
	mov	eax, DWORD PTR ___that$[ebp]
	mov	ecx, DWORD PTR [eax]
	mov	edx, DWORD PTR [eax+4]
	mov	eax, DWORD PTR _this$[ebp]
	mov	DWORD PTR [eax], ecx
	mov	DWORD PTR [eax+4], edx
	mov	eax, DWORD PTR _this$[ebp]
	pop	edi
	pop	esi
	pop	ebx
	mov	esp, ebp
	pop	ebp
	ret	4
??4QbStruct@GH3@@QAEAAU01@ABU01@@Z ENDP			; GH3::QbStruct::operator=
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
;	COMDAT ??4QbStructItem@GH3@@QAEAAU01@$$QAU01@@Z
_TEXT	SEGMENT
_this$ = -8						; size = 4
___that$ = 8						; size = 4
??4QbStructItem@GH3@@QAEAAU01@$$QAU01@@Z PROC		; GH3::QbStructItem::operator=, COMDAT
; _this$ = ecx
	push	ebp
	mov	ebp, esp
	sub	esp, 204				; 000000ccH
	push	ebx
	push	esi
	push	edi
	push	ecx
	lea	edi, DWORD PTR [ebp-204]
	mov	ecx, 51					; 00000033H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	pop	ecx
	mov	DWORD PTR _this$[ebp], ecx
	mov	eax, DWORD PTR _this$[ebp]
	mov	ecx, DWORD PTR ___that$[ebp]
	mov	dl, BYTE PTR [ecx]
	mov	BYTE PTR [eax], dl
	mov	eax, DWORD PTR _this$[ebp]
	mov	ecx, DWORD PTR ___that$[ebp]
	mov	dl, BYTE PTR [ecx+1]
	mov	BYTE PTR [eax+1], dl
	mov	eax, DWORD PTR _this$[ebp]
	mov	ecx, DWORD PTR ___that$[ebp]
	mov	dx, WORD PTR [ecx+2]
	mov	WORD PTR [eax+2], dx
	mov	eax, DWORD PTR _this$[ebp]
	mov	ecx, DWORD PTR ___that$[ebp]
	mov	edx, DWORD PTR [ecx+4]
	mov	DWORD PTR [eax+4], edx
	mov	eax, DWORD PTR _this$[ebp]
	mov	ecx, DWORD PTR ___that$[ebp]
	mov	edx, DWORD PTR [ecx+8]
	mov	DWORD PTR [eax+8], edx
	mov	eax, DWORD PTR _this$[ebp]
	mov	ecx, DWORD PTR ___that$[ebp]
	mov	edx, DWORD PTR [ecx+12]
	mov	DWORD PTR [eax+12], edx
	mov	eax, DWORD PTR _this$[ebp]
	pop	edi
	pop	esi
	pop	ebx
	mov	esp, ebp
	pop	ebp
	ret	4
??4QbStructItem@GH3@@QAEAAU01@$$QAU01@@Z ENDP		; GH3::QbStructItem::operator=
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
;	COMDAT ??4QbStructItem@GH3@@QAEAAU01@ABU01@@Z
_TEXT	SEGMENT
_this$ = -8						; size = 4
___that$ = 8						; size = 4
??4QbStructItem@GH3@@QAEAAU01@ABU01@@Z PROC		; GH3::QbStructItem::operator=, COMDAT
; _this$ = ecx
	push	ebp
	mov	ebp, esp
	sub	esp, 204				; 000000ccH
	push	ebx
	push	esi
	push	edi
	push	ecx
	lea	edi, DWORD PTR [ebp-204]
	mov	ecx, 51					; 00000033H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	pop	ecx
	mov	DWORD PTR _this$[ebp], ecx
	mov	eax, DWORD PTR ___that$[ebp]
	mov	ecx, DWORD PTR _this$[ebp]
	mov	edx, DWORD PTR [eax]
	mov	DWORD PTR [ecx], edx
	mov	edx, DWORD PTR [eax+4]
	mov	DWORD PTR [ecx+4], edx
	mov	edx, DWORD PTR [eax+8]
	mov	DWORD PTR [ecx+8], edx
	mov	eax, DWORD PTR [eax+12]
	mov	DWORD PTR [ecx+12], eax
	mov	eax, DWORD PTR _this$[ebp]
	pop	edi
	pop	esi
	pop	ebx
	mov	esp, ebp
	pop	ebp
	ret	4
??4QbStructItem@GH3@@QAEAAU01@ABU01@@Z ENDP		; GH3::QbStructItem::operator=
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
; File c:\windows\fastgh3\plugins\code\gh3\qbstruct.h
;	COMDAT ?Type@QbStructItem@GH3@@QAE?AW4QbValueType@2@XZ
_TEXT	SEGMENT
_this$ = -8						; size = 4
?Type@QbStructItem@GH3@@QAE?AW4QbValueType@2@XZ PROC	; GH3::QbStructItem::Type, COMDAT
; _this$ = ecx

; 47   : 		inline QbValueType Type() { return static_cast<QbValueType>(flags >> 1); }

	push	ebp
	mov	ebp, esp
	sub	esp, 204				; 000000ccH
	push	ebx
	push	esi
	push	edi
	push	ecx
	lea	edi, DWORD PTR [ebp-204]
	mov	ecx, 51					; 00000033H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	pop	ecx
	mov	DWORD PTR _this$[ebp], ecx
	mov	eax, DWORD PTR _this$[ebp]
	movsx	eax, BYTE PTR [eax+1]
	sar	eax, 1
	pop	edi
	pop	esi
	pop	ebx
	mov	esp, ebp
	pop	ebp
	ret	0
?Type@QbStructItem@GH3@@QAE?AW4QbValueType@2@XZ ENDP	; GH3::QbStructItem::Type
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
;	COMDAT ??4QbArray@GH3@@QAEAAU01@$$QAU01@@Z
_TEXT	SEGMENT
_this$ = -8						; size = 4
___that$ = 8						; size = 4
??4QbArray@GH3@@QAEAAU01@$$QAU01@@Z PROC		; GH3::QbArray::operator=, COMDAT
; _this$ = ecx
	push	ebp
	mov	ebp, esp
	sub	esp, 204				; 000000ccH
	push	ebx
	push	esi
	push	edi
	push	ecx
	lea	edi, DWORD PTR [ebp-204]
	mov	ecx, 51					; 00000033H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	pop	ecx
	mov	DWORD PTR _this$[ebp], ecx
	mov	eax, DWORD PTR _this$[ebp]
	mov	ecx, DWORD PTR ___that$[ebp]
	mov	dl, BYTE PTR [ecx]
	mov	BYTE PTR [eax], dl
	mov	eax, DWORD PTR _this$[ebp]
	mov	ecx, DWORD PTR ___that$[ebp]
	mov	dl, BYTE PTR [ecx+1]
	mov	BYTE PTR [eax+1], dl
	mov	eax, DWORD PTR _this$[ebp]
	mov	ecx, DWORD PTR ___that$[ebp]
	mov	dl, BYTE PTR [ecx+2]
	mov	BYTE PTR [eax+2], dl
	mov	eax, DWORD PTR _this$[ebp]
	mov	ecx, DWORD PTR ___that$[ebp]
	mov	dl, BYTE PTR [ecx+3]
	mov	BYTE PTR [eax+3], dl
	mov	eax, DWORD PTR _this$[ebp]
	mov	ecx, DWORD PTR ___that$[ebp]
	mov	edx, DWORD PTR [ecx+4]
	mov	DWORD PTR [eax+4], edx
	mov	eax, DWORD PTR _this$[ebp]
	mov	ecx, DWORD PTR ___that$[ebp]
	mov	edx, DWORD PTR [ecx+8]
	mov	DWORD PTR [eax+8], edx
	mov	eax, DWORD PTR _this$[ebp]
	pop	edi
	pop	esi
	pop	ebx
	mov	esp, ebp
	pop	ebp
	ret	4
??4QbArray@GH3@@QAEAAU01@$$QAU01@@Z ENDP		; GH3::QbArray::operator=
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
;	COMDAT ??4QbArray@GH3@@QAEAAU01@ABU01@@Z
_TEXT	SEGMENT
_this$ = -8						; size = 4
___that$ = 8						; size = 4
??4QbArray@GH3@@QAEAAU01@ABU01@@Z PROC			; GH3::QbArray::operator=, COMDAT
; _this$ = ecx
	push	ebp
	mov	ebp, esp
	sub	esp, 204				; 000000ccH
	push	ebx
	push	esi
	push	edi
	push	ecx
	lea	edi, DWORD PTR [ebp-204]
	mov	ecx, 51					; 00000033H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	pop	ecx
	mov	DWORD PTR _this$[ebp], ecx
	mov	eax, DWORD PTR ___that$[ebp]
	mov	ecx, DWORD PTR _this$[ebp]
	mov	edx, DWORD PTR [eax]
	mov	DWORD PTR [ecx], edx
	mov	edx, DWORD PTR [eax+4]
	mov	DWORD PTR [ecx+4], edx
	mov	eax, DWORD PTR [eax+8]
	mov	DWORD PTR [ecx+8], eax
	mov	eax, DWORD PTR _this$[ebp]
	pop	edi
	pop	esi
	pop	ebx
	mov	esp, ebp
	pop	ebp
	ret	4
??4QbArray@GH3@@QAEAAU01@ABU01@@Z ENDP			; GH3::QbArray::operator=
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
; File c:\windows\fastgh3\plugins\code\gh3\qbarray.h
;	COMDAT ?Length@QbArray@GH3@@QBEIXZ
_TEXT	SEGMENT
_this$ = -8						; size = 4
?Length@QbArray@GH3@@QBEIXZ PROC			; GH3::QbArray::Length, COMDAT
; _this$ = ecx

; 35   : 		inline uint32_t Length() const { return m_length;}

	push	ebp
	mov	ebp, esp
	sub	esp, 204				; 000000ccH
	push	ebx
	push	esi
	push	edi
	push	ecx
	lea	edi, DWORD PTR [ebp-204]
	mov	ecx, 51					; 00000033H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	pop	ecx
	mov	DWORD PTR _this$[ebp], ecx
	mov	eax, DWORD PTR _this$[ebp]
	mov	eax, DWORD PTR [eax+4]
	pop	edi
	pop	esi
	pop	ebx
	mov	esp, ebp
	pop	ebp
	ret	0
?Length@QbArray@GH3@@QBEIXZ ENDP			; GH3::QbArray::Length
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
; File c:\windows\fastgh3\plugins\code\gh3\qbarray.h
;	COMDAT ?Type@QbArray@GH3@@QBE?AW4QbValueType@2@XZ
_TEXT	SEGMENT
_this$ = -8						; size = 4
?Type@QbArray@GH3@@QBE?AW4QbValueType@2@XZ PROC		; GH3::QbArray::Type, COMDAT
; _this$ = ecx

; 34   : 		inline QbValueType Type() const { return m_type;}

	push	ebp
	mov	ebp, esp
	sub	esp, 204				; 000000ccH
	push	ebx
	push	esi
	push	edi
	push	ecx
	lea	edi, DWORD PTR [ebp-204]
	mov	ecx, 51					; 00000033H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	pop	ecx
	mov	DWORD PTR _this$[ebp], ecx
	mov	eax, DWORD PTR _this$[ebp]
	mov	al, BYTE PTR [eax+2]
	pop	edi
	pop	esi
	pop	ebx
	mov	esp, ebp
	pop	ebp
	ret	0
?Type@QbArray@GH3@@QBE?AW4QbValueType@2@XZ ENDP		; GH3::QbArray::Type
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
; File c:\windows\fastgh3\plugins\code\gh3\qbarray.h
;	COMDAT ?SetType@QbArray@GH3@@QAEXW4QbValueType@2@@Z
_TEXT	SEGMENT
_this$ = -8						; size = 4
_type$ = 8						; size = 1
?SetType@QbArray@GH3@@QAEXW4QbValueType@2@@Z PROC	; GH3::QbArray::SetType, COMDAT
; _this$ = ecx

; 33   : 		inline void SetType(QbValueType type) { m_type = type; }

	push	ebp
	mov	ebp, esp
	sub	esp, 204				; 000000ccH
	push	ebx
	push	esi
	push	edi
	push	ecx
	lea	edi, DWORD PTR [ebp-204]
	mov	ecx, 51					; 00000033H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	pop	ecx
	mov	DWORD PTR _this$[ebp], ecx
	mov	eax, DWORD PTR _this$[ebp]
	mov	cl, BYTE PTR _type$[ebp]
	mov	BYTE PTR [eax+2], cl
	pop	edi
	pop	esi
	pop	ebx
	mov	esp, ebp
	pop	ebp
	ret	4
?SetType@QbArray@GH3@@QAEXW4QbValueType@2@@Z ENDP	; GH3::QbArray::SetType
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
; File c:\windows\fastgh3\plugins\code\gh3\qbarray.h
;	COMDAT ?Get@QbArray@GH3@@QBEIH@Z
_TEXT	SEGMENT
_this$ = -8						; size = 4
_index$ = 8						; size = 4
?Get@QbArray@GH3@@QBEIH@Z PROC				; GH3::QbArray::Get, COMDAT
; _this$ = ecx

; 31   : 		inline uint32_t Get(int index) const { return (*this)[index]; }

	push	ebp
	mov	ebp, esp
	sub	esp, 204				; 000000ccH
	push	ebx
	push	esi
	push	edi
	push	ecx
	lea	edi, DWORD PTR [ebp-204]
	mov	ecx, 51					; 00000033H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	pop	ecx
	mov	DWORD PTR _this$[ebp], ecx
	mov	eax, DWORD PTR _index$[ebp]
	push	eax
	mov	ecx, DWORD PTR _this$[ebp]
	call	??AQbArray@GH3@@QBEIH@Z			; GH3::QbArray::operator[]
	pop	edi
	pop	esi
	pop	ebx
	add	esp, 204				; 000000ccH
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	4
?Get@QbArray@GH3@@QBEIH@Z ENDP				; GH3::QbArray::Get
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
; File c:\windows\fastgh3\plugins\code\gh3\qbarray.h
;	COMDAT ?Set@QbArray@GH3@@QAEXHI@Z
_TEXT	SEGMENT
_this$ = -8						; size = 4
_index$ = 8						; size = 4
_value$ = 12						; size = 4
?Set@QbArray@GH3@@QAEXHI@Z PROC				; GH3::QbArray::Set, COMDAT
; _this$ = ecx

; 30   : 		inline void Set(int index, uint32_t value) { (*this)[index] = value; }

	push	ebp
	mov	ebp, esp
	sub	esp, 204				; 000000ccH
	push	ebx
	push	esi
	push	edi
	push	ecx
	lea	edi, DWORD PTR [ebp-204]
	mov	ecx, 51					; 00000033H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	pop	ecx
	mov	DWORD PTR _this$[ebp], ecx
	mov	eax, DWORD PTR _index$[ebp]
	push	eax
	mov	ecx, DWORD PTR _this$[ebp]
	call	??AQbArray@GH3@@QAEAAIH@Z		; GH3::QbArray::operator[]
	mov	ecx, DWORD PTR _value$[ebp]
	mov	DWORD PTR [eax], ecx
	pop	edi
	pop	esi
	pop	ebx
	add	esp, 204				; 000000ccH
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	8
?Set@QbArray@GH3@@QAEXHI@Z ENDP				; GH3::QbArray::Set
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
;	COMDAT ??4QbVector@GH3@@QAEAAU01@$$QAU01@@Z
_TEXT	SEGMENT
_$S2$1 = -20						; size = 4
_this$ = -8						; size = 4
___that$ = 8						; size = 4
??4QbVector@GH3@@QAEAAU01@$$QAU01@@Z PROC		; GH3::QbVector::operator=, COMDAT
; _this$ = ecx
	push	ebp
	mov	ebp, esp
	sub	esp, 216				; 000000d8H
	push	ebx
	push	esi
	push	edi
	push	ecx
	lea	edi, DWORD PTR [ebp-216]
	mov	ecx, 54					; 00000036H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	pop	ecx
	mov	DWORD PTR _this$[ebp], ecx
	mov	DWORD PTR _$S2$1[ebp], 0
	jmp	SHORT $LN4@operator
$LN2@operator:
	mov	eax, DWORD PTR _$S2$1[ebp]
	add	eax, 1
	mov	DWORD PTR _$S2$1[ebp], eax
$LN4@operator:
	cmp	DWORD PTR _$S2$1[ebp], 1
	jae	SHORT $LN3@operator
	mov	eax, DWORD PTR _this$[ebp]
	add	eax, DWORD PTR _$S2$1[ebp]
	mov	ecx, DWORD PTR ___that$[ebp]
	add	ecx, DWORD PTR _$S2$1[ebp]
	mov	dl, BYTE PTR [ecx]
	mov	BYTE PTR [eax], dl
	jmp	SHORT $LN2@operator
$LN3@operator:
	mov	eax, DWORD PTR _this$[ebp]
	mov	ecx, DWORD PTR ___that$[ebp]
	mov	dl, BYTE PTR [ecx+1]
	mov	BYTE PTR [eax+1], dl
	mov	eax, DWORD PTR _this$[ebp]
	mov	ecx, DWORD PTR ___that$[ebp]
	mov	edx, DWORD PTR [ecx+4]
	mov	DWORD PTR [eax+4], edx
	mov	eax, DWORD PTR _this$[ebp]
	mov	ecx, DWORD PTR ___that$[ebp]
	mov	edx, DWORD PTR [ecx+8]
	mov	DWORD PTR [eax+8], edx
	mov	eax, DWORD PTR _this$[ebp]
	mov	ecx, DWORD PTR ___that$[ebp]
	mov	edx, DWORD PTR [ecx+12]
	mov	DWORD PTR [eax+12], edx
	mov	eax, DWORD PTR _this$[ebp]
	pop	edi
	pop	esi
	pop	ebx
	mov	esp, ebp
	pop	ebp
	ret	4
??4QbVector@GH3@@QAEAAU01@$$QAU01@@Z ENDP		; GH3::QbVector::operator=
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
;	COMDAT ??4QbVector@GH3@@QAEAAU01@ABU01@@Z
_TEXT	SEGMENT
_this$ = -8						; size = 4
___that$ = 8						; size = 4
??4QbVector@GH3@@QAEAAU01@ABU01@@Z PROC			; GH3::QbVector::operator=, COMDAT
; _this$ = ecx
	push	ebp
	mov	ebp, esp
	sub	esp, 204				; 000000ccH
	push	ebx
	push	esi
	push	edi
	push	ecx
	lea	edi, DWORD PTR [ebp-204]
	mov	ecx, 51					; 00000033H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	pop	ecx
	mov	DWORD PTR _this$[ebp], ecx
	mov	eax, DWORD PTR ___that$[ebp]
	mov	ecx, DWORD PTR _this$[ebp]
	mov	edx, DWORD PTR [eax]
	mov	DWORD PTR [ecx], edx
	mov	edx, DWORD PTR [eax+4]
	mov	DWORD PTR [ecx+4], edx
	mov	edx, DWORD PTR [eax+8]
	mov	DWORD PTR [ecx+8], edx
	mov	eax, DWORD PTR [eax+12]
	mov	DWORD PTR [ecx+12], eax
	mov	eax, DWORD PTR _this$[ebp]
	pop	edi
	pop	esi
	pop	ebx
	mov	esp, ebp
	pop	ebp
	ret	4
??4QbVector@GH3@@QAEAAU01@ABU01@@Z ENDP			; GH3::QbVector::operator=
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
;	COMDAT ??4QbPair@GH3@@QAEAAU01@$$QAU01@@Z
_TEXT	SEGMENT
_$S1$1 = -20						; size = 4
_this$ = -8						; size = 4
___that$ = 8						; size = 4
??4QbPair@GH3@@QAEAAU01@$$QAU01@@Z PROC			; GH3::QbPair::operator=, COMDAT
; _this$ = ecx
	push	ebp
	mov	ebp, esp
	sub	esp, 216				; 000000d8H
	push	ebx
	push	esi
	push	edi
	push	ecx
	lea	edi, DWORD PTR [ebp-216]
	mov	ecx, 54					; 00000036H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	pop	ecx
	mov	DWORD PTR _this$[ebp], ecx
	mov	DWORD PTR _$S1$1[ebp], 0
	jmp	SHORT $LN4@operator
$LN2@operator:
	mov	eax, DWORD PTR _$S1$1[ebp]
	add	eax, 1
	mov	DWORD PTR _$S1$1[ebp], eax
$LN4@operator:
	cmp	DWORD PTR _$S1$1[ebp], 1
	jae	SHORT $LN3@operator
	mov	eax, DWORD PTR _this$[ebp]
	add	eax, DWORD PTR _$S1$1[ebp]
	mov	ecx, DWORD PTR ___that$[ebp]
	add	ecx, DWORD PTR _$S1$1[ebp]
	mov	dl, BYTE PTR [ecx]
	mov	BYTE PTR [eax], dl
	jmp	SHORT $LN2@operator
$LN3@operator:
	mov	eax, DWORD PTR _this$[ebp]
	mov	ecx, DWORD PTR ___that$[ebp]
	mov	dl, BYTE PTR [ecx+1]
	mov	BYTE PTR [eax+1], dl
	mov	eax, DWORD PTR _this$[ebp]
	mov	ecx, DWORD PTR ___that$[ebp]
	mov	edx, DWORD PTR [ecx+4]
	mov	DWORD PTR [eax+4], edx
	mov	eax, DWORD PTR _this$[ebp]
	mov	ecx, DWORD PTR ___that$[ebp]
	mov	edx, DWORD PTR [ecx+8]
	mov	DWORD PTR [eax+8], edx
	mov	eax, DWORD PTR _this$[ebp]
	pop	edi
	pop	esi
	pop	ebx
	mov	esp, ebp
	pop	ebp
	ret	4
??4QbPair@GH3@@QAEAAU01@$$QAU01@@Z ENDP			; GH3::QbPair::operator=
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
;	COMDAT ??4QbPair@GH3@@QAEAAU01@ABU01@@Z
_TEXT	SEGMENT
_this$ = -8						; size = 4
___that$ = 8						; size = 4
??4QbPair@GH3@@QAEAAU01@ABU01@@Z PROC			; GH3::QbPair::operator=, COMDAT
; _this$ = ecx
	push	ebp
	mov	ebp, esp
	sub	esp, 204				; 000000ccH
	push	ebx
	push	esi
	push	edi
	push	ecx
	lea	edi, DWORD PTR [ebp-204]
	mov	ecx, 51					; 00000033H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	pop	ecx
	mov	DWORD PTR _this$[ebp], ecx
	mov	eax, DWORD PTR ___that$[ebp]
	mov	ecx, DWORD PTR _this$[ebp]
	mov	edx, DWORD PTR [eax]
	mov	DWORD PTR [ecx], edx
	mov	edx, DWORD PTR [eax+4]
	mov	DWORD PTR [ecx+4], edx
	mov	eax, DWORD PTR [eax+8]
	mov	DWORD PTR [ecx+8], eax
	mov	eax, DWORD PTR _this$[ebp]
	pop	edi
	pop	esi
	pop	ebx
	mov	esp, ebp
	pop	ebp
	ret	4
??4QbPair@GH3@@QAEAAU01@ABU01@@Z ENDP			; GH3::QbPair::operator=
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
;	COMDAT ??4QbKey@GH3@@QAEAAU01@ABU01@@Z
_TEXT	SEGMENT
_this$ = -8						; size = 4
___that$ = 8						; size = 4
??4QbKey@GH3@@QAEAAU01@ABU01@@Z PROC			; GH3::QbKey::operator=, COMDAT
; _this$ = ecx
	push	ebp
	mov	ebp, esp
	sub	esp, 204				; 000000ccH
	push	ebx
	push	esi
	push	edi
	push	ecx
	lea	edi, DWORD PTR [ebp-204]
	mov	ecx, 51					; 00000033H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	pop	ecx
	mov	DWORD PTR _this$[ebp], ecx
	mov	eax, DWORD PTR ___that$[ebp]
	mov	ecx, DWORD PTR [eax]
	mov	edx, DWORD PTR _this$[ebp]
	mov	DWORD PTR [edx], ecx
	mov	eax, DWORD PTR _this$[ebp]
	pop	edi
	pop	esi
	pop	ebx
	mov	esp, ebp
	pop	ebp
	ret	4
??4QbKey@GH3@@QAEAAU01@ABU01@@Z ENDP			; GH3::QbKey::operator=
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
; File c:\windows\fastgh3\plugins\code\gh3\qbkey.h
;	COMDAT ??4QbKey@GH3@@QAEAAU01@I@Z
_TEXT	SEGMENT
_this$ = -8						; size = 4
_rhs$ = 8						; size = 4
??4QbKey@GH3@@QAEAAU01@I@Z PROC				; GH3::QbKey::operator=, COMDAT
; _this$ = ecx

; 111  : 		inline QbKey& operator=(const uint32_t rhs) { m_key = rhs; return *this; };

	push	ebp
	mov	ebp, esp
	sub	esp, 204				; 000000ccH
	push	ebx
	push	esi
	push	edi
	push	ecx
	lea	edi, DWORD PTR [ebp-204]
	mov	ecx, 51					; 00000033H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	pop	ecx
	mov	DWORD PTR _this$[ebp], ecx
	mov	eax, DWORD PTR _this$[ebp]
	mov	ecx, DWORD PTR _rhs$[ebp]
	mov	DWORD PTR [eax], ecx
	mov	eax, DWORD PTR _this$[ebp]
	pop	edi
	pop	esi
	pop	ebx
	mov	esp, ebp
	pop	ebp
	ret	4
??4QbKey@GH3@@QAEAAU01@I@Z ENDP				; GH3::QbKey::operator=
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
; File c:\windows\fastgh3\plugins\code\gh3\qbkey.h
;	COMDAT ??BQbKey@GH3@@QBEIXZ
_TEXT	SEGMENT
_this$ = -8						; size = 4
??BQbKey@GH3@@QBEIXZ PROC				; GH3::QbKey::operator unsigned int, COMDAT
; _this$ = ecx

; 108  : 		inline constexpr operator uint32_t() const { return m_key; }

	push	ebp
	mov	ebp, esp
	sub	esp, 204				; 000000ccH
	push	ebx
	push	esi
	push	edi
	push	ecx
	lea	edi, DWORD PTR [ebp-204]
	mov	ecx, 51					; 00000033H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	pop	ecx
	mov	DWORD PTR _this$[ebp], ecx
	mov	eax, DWORD PTR _this$[ebp]
	mov	eax, DWORD PTR [eax]
	pop	edi
	pop	esi
	pop	ebx
	mov	esp, ebp
	pop	ebp
	ret	0
??BQbKey@GH3@@QBEIXZ ENDP				; GH3::QbKey::operator unsigned int
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
; File c:\windows\fastgh3\plugins\code\gh3\qbkey.h
;	COMDAT ??0QbKey@GH3@@QAE@PBD@Z
_TEXT	SEGMENT
_this$ = -8						; size = 4
_key$ = 8						; size = 4
??0QbKey@GH3@@QAE@PBD@Z PROC				; GH3::QbKey::QbKey, COMDAT
; _this$ = ecx

; 105  : 		constexpr QbKey(const char *key) : m_key(crc32::hash(key)) {};

	push	ebp
	mov	ebp, esp
	sub	esp, 204				; 000000ccH
	push	ebx
	push	esi
	push	edi
	push	ecx
	lea	edi, DWORD PTR [ebp-204]
	mov	ecx, 51					; 00000033H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	pop	ecx
	mov	DWORD PTR _this$[ebp], ecx
	push	-1
	mov	eax, DWORD PTR _key$[ebp]
	push	eax
	call	?hash@crc32@GH3@@YAIPBDI@Z		; GH3::crc32::hash
	add	esp, 8
	mov	ecx, DWORD PTR _this$[ebp]
	mov	DWORD PTR [ecx], eax
	mov	eax, DWORD PTR _this$[ebp]
	pop	edi
	pop	esi
	pop	ebx
	add	esp, 204				; 000000ccH
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	4
??0QbKey@GH3@@QAE@PBD@Z ENDP				; GH3::QbKey::QbKey
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
; File c:\windows\fastgh3\plugins\code\gh3\qbkey.h
;	COMDAT ??0QbKey@GH3@@QAE@I@Z
_TEXT	SEGMENT
_this$ = -8						; size = 4
_key$ = 8						; size = 4
??0QbKey@GH3@@QAE@I@Z PROC				; GH3::QbKey::QbKey, COMDAT
; _this$ = ecx

; 102  : 		constexpr QbKey(const uint32_t key) : m_key(key) {};

	push	ebp
	mov	ebp, esp
	sub	esp, 204				; 000000ccH
	push	ebx
	push	esi
	push	edi
	push	ecx
	lea	edi, DWORD PTR [ebp-204]
	mov	ecx, 51					; 00000033H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	pop	ecx
	mov	DWORD PTR _this$[ebp], ecx
	mov	eax, DWORD PTR _this$[ebp]
	mov	ecx, DWORD PTR _key$[ebp]
	mov	DWORD PTR [eax], ecx
	mov	eax, DWORD PTR _this$[ebp]
	pop	edi
	pop	esi
	pop	ebx
	mov	esp, ebp
	pop	ebp
	ret	4
??0QbKey@GH3@@QAE@I@Z ENDP				; GH3::QbKey::QbKey
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
; File c:\windows\fastgh3\plugins\code\gh3\qbkey.h
;	COMDAT ??0QbKey@GH3@@QAE@ABU01@@Z
_TEXT	SEGMENT
_this$ = -8						; size = 4
_rhs$ = 8						; size = 4
??0QbKey@GH3@@QAE@ABU01@@Z PROC				; GH3::QbKey::QbKey, COMDAT
; _this$ = ecx

; 99   : 		constexpr QbKey(const QbKey &rhs) : m_key(rhs.m_key) {};

	push	ebp
	mov	ebp, esp
	sub	esp, 204				; 000000ccH
	push	ebx
	push	esi
	push	edi
	push	ecx
	lea	edi, DWORD PTR [ebp-204]
	mov	ecx, 51					; 00000033H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	pop	ecx
	mov	DWORD PTR _this$[ebp], ecx
	mov	eax, DWORD PTR _this$[ebp]
	mov	ecx, DWORD PTR _rhs$[ebp]
	mov	edx, DWORD PTR [ecx]
	mov	DWORD PTR [eax], edx
	mov	eax, DWORD PTR _this$[ebp]
	pop	edi
	pop	esi
	pop	ebx
	mov	esp, ebp
	pop	ebp
	ret	4
??0QbKey@GH3@@QAE@ABU01@@Z ENDP				; GH3::QbKey::QbKey
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
; File c:\windows\fastgh3\plugins\code\gh3\qbkey.h
;	COMDAT ??0QbKey@GH3@@QAE@XZ
_TEXT	SEGMENT
_this$ = -8						; size = 4
??0QbKey@GH3@@QAE@XZ PROC				; GH3::QbKey::QbKey, COMDAT
; _this$ = ecx

; 97   : 		constexpr QbKey() : m_key(0) {};

	push	ebp
	mov	ebp, esp
	sub	esp, 204				; 000000ccH
	push	ebx
	push	esi
	push	edi
	push	ecx
	lea	edi, DWORD PTR [ebp-204]
	mov	ecx, 51					; 00000033H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	pop	ecx
	mov	DWORD PTR _this$[ebp], ecx
	mov	eax, DWORD PTR _this$[ebp]
	mov	DWORD PTR [eax], 0
	mov	eax, DWORD PTR _this$[ebp]
	pop	edi
	pop	esi
	pop	ebx
	mov	esp, ebp
	pop	ebp
	ret	0
??0QbKey@GH3@@QAE@XZ ENDP				; GH3::QbKey::QbKey
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
; File c:\windows\fastgh3\plugins\code\gh3\qbkey.h
;	COMDAT ?hash@crc32@GH3@@YAIPBDI@Z
_TEXT	SEGMENT
tv74 = -200						; size = 4
tv75 = -196						; size = 4
_key$ = 8						; size = 4
_previousKey$ = 12					; size = 4
?hash@crc32@GH3@@YAIPBDI@Z PROC				; GH3::crc32::hash, COMDAT

; 76   : 		{

	push	ebp
	mov	ebp, esp
	sub	esp, 200				; 000000c8H
	push	ebx
	push	esi
	push	edi
	lea	edi, DWORD PTR [ebp-200]
	mov	ecx, 50					; 00000032H
	mov	eax, -858993460				; ccccccccH
	rep stosd

; 77   : 			return	(!key) ? 0 :

	cmp	DWORD PTR _key$[ebp], 0
	jne	SHORT $LN5@hash
	mov	DWORD PTR tv75[ebp], 0
	jmp	SHORT $LN6@hash
$LN5@hash:
	mov	eax, DWORD PTR _key$[ebp]
	movsx	ecx, BYTE PTR [eax]
	test	ecx, ecx
	jne	SHORT $LN3@hash
	mov	edx, DWORD PTR _previousKey$[ebp]
	mov	DWORD PTR tv74[ebp], edx
	jmp	SHORT $LN4@hash
$LN3@hash:
	mov	eax, DWORD PTR _previousKey$[ebp]
	push	eax
	mov	ecx, DWORD PTR _key$[ebp]
	movzx	edx, BYTE PTR [ecx]
	push	edx
	call	?hashChar@crc32@GH3@@YAIDI@Z		; GH3::crc32::hashChar
	add	esp, 8
	push	eax
	mov	eax, DWORD PTR _key$[ebp]
	add	eax, 1
	push	eax
	call	?hash@crc32@GH3@@YAIPBDI@Z		; GH3::crc32::hash
	add	esp, 8
	mov	DWORD PTR tv74[ebp], eax
$LN4@hash:
	mov	ecx, DWORD PTR tv74[ebp]
	mov	DWORD PTR tv75[ebp], ecx
$LN6@hash:
	mov	eax, DWORD PTR tv75[ebp]

; 78   : 					(*key == '\0') ? previousKey :
; 79   : 					(hash(key + 1, hashChar(*key, previousKey)));
; 80   : 		}

	pop	edi
	pop	esi
	pop	ebx
	add	esp, 200				; 000000c8H
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	0
?hash@crc32@GH3@@YAIPBDI@Z ENDP				; GH3::crc32::hash
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
; File c:\windows\fastgh3\plugins\code\gh3\qbkey.h
;	COMDAT ?hashChar@crc32@GH3@@YAIDI@Z
_TEXT	SEGMENT
_c$ = 8							; size = 1
_crc$ = 12						; size = 4
?hashChar@crc32@GH3@@YAIDI@Z PROC			; GH3::crc32::hashChar, COMDAT

; 71   : 		{

	push	ebp
	mov	ebp, esp
	sub	esp, 192				; 000000c0H
	push	ebx
	push	esi
	push	edi
	lea	edi, DWORD PTR [ebp-192]
	mov	ecx, 48					; 00000030H
	mov	eax, -858993460				; ccccccccH
	rep stosd

; 72   : 			return tab[(crc ^ fixChar(c)) & 0xFF] ^ (crc >> 8);

	movzx	eax, BYTE PTR _c$[ebp]
	push	eax
	call	?fixChar@crc32@GH3@@YADD@Z		; GH3::crc32::fixChar
	add	esp, 4
	movsx	ecx, al
	xor	ecx, DWORD PTR _crc$[ebp]
	and	ecx, 255				; 000000ffH
	mov	eax, DWORD PTR _crc$[ebp]
	shr	eax, 8
	xor	eax, DWORD PTR ?tab@crc32@GH3@@3QBIB[ecx*4]

; 73   : 		}

	pop	edi
	pop	esi
	pop	ebx
	add	esp, 192				; 000000c0H
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	0
?hashChar@crc32@GH3@@YAIDI@Z ENDP			; GH3::crc32::hashChar
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
; File c:\windows\fastgh3\plugins\code\gh3\qbkey.h
;	COMDAT ?fixChar@crc32@GH3@@YADD@Z
_TEXT	SEGMENT
tv72 = -197						; size = 1
tv74 = -196						; size = 4
_c$ = 8							; size = 1
?fixChar@crc32@GH3@@YADD@Z PROC				; GH3::crc32::fixChar, COMDAT

; 64   : 		{

	push	ebp
	mov	ebp, esp
	sub	esp, 200				; 000000c8H
	push	ebx
	push	esi
	push	edi
	lea	edi, DWORD PTR [ebp-200]
	mov	ecx, 50					; 00000032H
	mov	eax, -858993460				; ccccccccH
	rep stosd

; 65   : 			return	(c >= 'A' && c <= 'Z') ? (c + 32) :

	movsx	eax, BYTE PTR _c$[ebp]
	cmp	eax, 65					; 00000041H
	jl	SHORT $LN3@fixChar
	movsx	ecx, BYTE PTR _c$[ebp]
	cmp	ecx, 90					; 0000005aH
	jg	SHORT $LN3@fixChar
	movsx	edx, BYTE PTR _c$[ebp]
	add	edx, 32					; 00000020H
	mov	DWORD PTR tv74[ebp], edx
	jmp	SHORT $LN6@fixChar
$LN3@fixChar:
	movsx	eax, BYTE PTR _c$[ebp]
	cmp	eax, 47					; 0000002fH
	jne	SHORT $LN4@fixChar
	mov	BYTE PTR tv72[ebp], 92			; 0000005cH
	jmp	SHORT $LN5@fixChar
$LN4@fixChar:
	mov	cl, BYTE PTR _c$[ebp]
	mov	BYTE PTR tv72[ebp], cl
$LN5@fixChar:
	movsx	edx, BYTE PTR tv72[ebp]
	mov	DWORD PTR tv74[ebp], edx
$LN6@fixChar:
	mov	al, BYTE PTR tv74[ebp]

; 66   : 				(c == '/') ? '\\' :
; 67   : 				c;
; 68   : 		}

	pop	edi
	pop	esi
	pop	ebx
	mov	esp, ebp
	pop	ebp
	ret	0
?fixChar@crc32@GH3@@YADD@Z ENDP				; GH3::crc32::fixChar
_TEXT	ENDS
END
